### ISSUE TITLE
Proposal: Coding to Development

### ISSUE THREAD

**Issue by funkyidol** [gdgnewdelhi/talks#1]
A talk on how coders can grow themselves to be developers.

It not only focuses on technical growth but personal and relationship growth.

**Comment by rohanraarora** [comment]
Hey Kshitiz,

Thank you for submitting the proposal. Can you share the estimated duration of your talk?

Thanks

**Comment by rohanraarora** [comment]
Hey Kshitij

We are planning to organize a GDG meetup on 19th Feb. If you are available, let us know and we can confirm this.

Thanks

**Comment by funkyidol** [comment]
Hi Rohan,

The duration of the talk will be easily an hour, maybe more.

For the 19th Feb event, I wont be available as I'm a bit tied up till march, maybe longer.

Cheers and All the best for the event.

**Comment by rohanraarora** [comment]
Thanks. Let's do this sometime later then. Closing the issue for now, reopen this when you are available.
