### ISSUE TITLE
Go(lang) for backend developers

### ISSUE THREAD

**Issue by DesmondANIMUS** [gdgnewdelhi/talks#18]
- [x] Title: Go(lang) for backend developers
- [x] Short Abstract: The talk will cover Golang as first programming language for aspiring back-end developers, it's future and a restful API service helping people to Go for it.
- [x] Full description/topics covered: The topics that I am aiming to cover are: Why **Go**?, a simple restful API and intro to http/2 standard. This should help everyone get started with backend services development so that they can in future develop highly concurrent services / web apps.
- [x] Duration: 20 Minutes
- [x] Level of expertise required: Beginner
- [x] Special requirements: None

**Comment by arpansac** [comment]
Hey @DesmondANIMUS 
We're planning a meetup this weekend on 28th May, 2017. Would you be available?

**Comment by DesmondANIMUS** [comment]
Hey @arpansac, thank you for considering my proposal. :)

I would love to be there; but I am afraid I have my last external exam on the very next day that is on 29th May, so it wouldn't​ be possible for me on that day.

**Comment by arpansac** [comment]
Hi @DesmondANIMUS, thanks for replying, we'd then reach out to you after your exams! All the best :)

**Comment by arpansac** [comment]
Hey @DesmondANIMUS would you be available this Sunday (4th June, 10am-12pm)?

**Comment by DesmondANIMUS** [comment]
Yeah, I'm free on that day ^_^

**Comment by arpansac** [comment]
Great, then I'll request you to share your email id here or to me on our meetup.com page asap. We'll take things forward from there after I have a conversation on phone with you! Hoping we meet this Sunday for a great session, we're running out of time!

**Comment by DesmondANIMUS** [comment]
Sure thing, will do that now. :)

**Comment by rohanraarora** [comment]
Closing this issue. Please add your slides and any other content to https://github.com/gdgnewdelhi/talks
