### ISSUE TITLE
Is this an official group?

### ISSUE THREAD

**Issue by garora** [gdgnewdelhi/talks#20]
Hi all,
Is this an official group?

**Comment by nisrulz** [comment]
Yup. Here is the [official listing](https://developers.google.com/groups/chapter/114576537688641864561/)

How can we help you?

**Comment by garora** [comment]
@nisrulz - thanks for the heads up. How can be a member of this group and what are the guidelines to start participation. It would be nice if someone help me to understand this group, I am available at twitter handle: @g_arora

**Comment by arpansac** [comment]
Hi @garora you can connect with us on our meetup group here: https://www.meetup.com/gdgnewdelhi/
