### ISSUE TITLE
Workshop for Git and GSoC

### ISSUE THREAD

**Issue by free4murad** [gdgnewdelhi/talks#3]
As GSoC 2017 is around the corner I suggest that you should conduct a seminar on GSoC.
It will help students.
@rohanraarora what do you think?

**Comment by nisrulz** [comment]
@free4murad we do have that topic in mind. We would like someone to propose a talk on their own this time, otherwise we would anyways bring on some speakers for our meetup. 😄

**Comment by rohanraarora** [comment]
Closing this for now.
