### ISSUE TITLE
Proposal: UX Design Talk

### ISSUE THREAD

**Issue by punitweb** [gdgnewdelhi/talks#4]
I would love to give a talk on UX and UI design at your local meetup. I'm an experienced web designer, UI and UX designer. 
![pup-sack-1](https://cloud.githubusercontent.com/assets/13645369/23820694/92635450-0644-11e7-8aba-42397080a517.jpg)
![incline-insta](https://cloud.githubusercontent.com/assets/13645369/23820695/926a25b4-0644-11e7-9db1-fa466fb35687.jpg)
![reflect](https://cloud.githubusercontent.com/assets/13645369/23820696/926ab556-0644-11e7-853c-61f3c0ee61de.jpg)
![lemon-time](https://cloud.githubusercontent.com/assets/13645369/23820697/926eed1a-0644-11e7-84d2-522232b24cbc.jpg)
![rose](https://cloud.githubusercontent.com/assets/13645369/23820698/9271dc0a-0644-11e7-814a-01aa899d7b5a.jpg)
![face-mash](https://cloud.githubusercontent.com/assets/13645369/23820699/927636ec-0644-11e7-88b4-f3be17ba8864.jpg)

**Comment by nisrulz** [comment]
Hi @punitweb , can you give me a complete description your proposed talk and what you would be covering in it?

**Comment by punitweb** [comment]
I will be focusing on how app/web designers and developers can use intelligent and fast UX and UI to get more retention time on their apps. I will be discussing mistakes developers make when handling solo projects and how to develop a better UI for the current market. The developers will take away a good knowledge base of UX and what their users really want. I am also young, so I will be able to relate with all the young developers in the room and answer some very valuable questions from the group. As we designers say, **a bit of UX and UI knowledge never hurts**.

**Comment by punitweb** [comment]
I will also be covering key points like:-

- Prototyping - do's and dont's
- How much is too much design?
- What do user's really want today
- The secret to keeping the user focused on your app
These are the key points and areas I'll be covering.

**Comment by rohanraarora** [comment]
Hi Puneet,
Can you do this talk on 16th April?

**Comment by punitweb** [comment]
Most definitely Rohan.
Thanks for the opportunity.

PS. it's Punit

**Comment by rohanraarora** [comment]
Awesome Punit 😄 . Sorry for the wrong name 😬 
Let's do it on 16th then. We will publish the event next week
We are planning to have a codelab on Android too along with this one, So you can expect a mixed audience of android and web developers. Also can you share the estimated duration of your talk?

**Comment by punitweb** [comment]
Well , I would let you decide the time frame as there will be other
speakers too. I would like to balance my talk with the other speakers.

**Comment by punitweb** [comment]
Any updates for confirmation for the 16th? @rohanraarora

**Comment by rohanraarora** [comment]
Hey @punitweb . The WTM event is being done on 16th so let's do this talk in the next meetup.

**Comment by punitweb** [comment]
Sure @rohanraarora

**Comment by rohanraarora** [comment]
Rescheduling it on 20th May for [IO Extended New Delhi](https://www.meetup.com/GDGNewDelhi/events/239486318/)

**Comment by punitweb** [comment]
**Great!** Thanks

**Comment by nisrulz** [comment]
@punitweb whats the total time for your talk?

**Comment by punitweb** [comment]
The title is " **UX and UI BLOOM** "  and duration is 1 hour
( i can shorten or lengthen it according to the even'ts requirements )

**Comment by nisrulz** [comment]
Awesome, we are putting that up. Thanks 😄

**Comment by nisrulz** [comment]
@punitweb The session was really good, hearing good things from people. Could you open a pull request and add your talk to the main readme file for this repo with all details. If now we can do it for you too.

Once done we will close this issue. Thank you for speaking at our event and helping the community by imparting your knowledge 😄

**Comment by punitweb** [comment]
Would be great if you could do it

**Comment by nisrulz** [comment]
This is delivered and Information regarding it is up on the main readme. Closing this now.
