### ISSUE TITLE
Proposal: Google Cloud demonstration, hands on with Google BigQuery

### ISSUE THREAD

**Issue by prabh-me** [gdgnewdelhi/talks#7]
* Features of Google Cloud.
* Data pipelining, analysis and Machine Learning.
* Digging deep into Google BigQuery.
* Linking Firebase with BigQuery to dump user events data.
* Google Cloud APIs.

**Comment by rohanraarora** [comment]
Hey Prabhjot,

We are planning to organize GCP Next Recap event on 2nd April. We can include this into our agenda if you are available.

**Comment by prabh-me** [comment]
Cool. Would be available on 2nd April.

**Comment by rohanraarora** [comment]
Scheduled for [**GCP Next Extended New Delhi**](https://www.facebook.com/events/287461618343025/).

**Comment by imrshu** [comment]
It was an awesome GCP Event #Coding Ninjas. :)

**Comment by prabh-me** [comment]
Thanks

**Comment by nisrulz** [comment]
@prabh-me open up a PR with required details to add your info in the readme of this repo.

**Comment by nisrulz** [comment]
Closing as this is done and also listed in the repo. Thank you @prabh-me for the session. Looking forward to more such sessions/talks from you in the future.
